---
- name: generate ssh key
  user: name="{{ user }}" generate_ssh_key=yes ssh_key_file=.ssh/id_rsa_github

- name: create script from template
  template: src=".ssh/config.j2" dest="~/.ssh/config" mode=0644
- template: src="add_ssh_key.rb.j2" dest="~/add_ssh_key.rb"

- name: exec script
  shell: "bash -lc 'ruby ~/add_ssh_key.rb {{ github.user }} {{ github.access_token }}'"
  register: result
  changed_when: result.stdout == "changed"
