---
- name: install ndenv
  shell: "bash -lc 'echo N | anyenv install ndenv'"
  register: result
  failed_when: False
  changed_when: result.rc == 0

- name: install ndenv-yarn-install
  git: repo=https://github.com/pine/ndenv-yarn-install.git dest=~/.anyenv/envs/ndenv/plugins/ndenv-yarn-install

- name: install node
  shell: "bash -lc 'echo no | ndenv install {{ node_version }}'"
  register: result
  failed_when: False
  changed_when: result.rc == 0

- name: set default node version
  shell: "bash -lc 'ndenv global {{ node_version }}'"
  when: result.rc == 0

- name: add to environment variable
  blockinfile:
    dest: ~/.profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK for node"
    content: |
      PATH="./node_modules/.bin:$PATH"
