---
- name: install apt packeges
  apt: pkg="{{ item }}" update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: install rbenv
  shell: "bash -lc 'echo N | anyenv install rbenv'"
  register: result
  failed_when: False
  changed_when: result.rc == 0

- name: install ruby
  shell: "bash -lc 'echo no | rbenv install {{ ruby_version }}'"
  register: result
  failed_when: False
  changed_when: result.rc == 0

- name: set default ruby version
  shell: "bash -lc 'rbenv global {{ ruby_version }}'"
  when: result.rc == 0

- name: install bundler
  gem: name=bundler user_install=no
