---
- name: install apt packeges
  apt: pkg="{{ item }}" update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: install ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: add to environment variable
  blockinfile:
    dest: ~/.profile
    content: |
      PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"

- name: install ruby
  shell: "bash -lc 'echo no | rbenv install {{ ruby_version }}'"
  register: result
  failed_when: False
  changed_when: result.rc == 0

- name: set default ruby version
  shell: "bash -lc 'rbenv global {{ ruby_version }}'"
  when: result.rc == 0

- name: install bundler
  gem: name=bundler user_install=no
